<a href="https://colab.research.google.com/github/nncohens/DATA-690-WANG/blob/master/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import random
import numpy as np 
#arr = np.random.rand(10, 10) 
#arr

In [1]:
from numpy import random

x = random.randint(10, size=(10, 10))

print(x)

[[0 6 8 3 9 4 6 6 1 0]
 [0 1 0 2 2 7 4 2 4 9]
 [5 4 9 8 3 2 3 7 9 2]
 [0 0 4 4 4 6 2 9 1 5]
 [5 3 8 9 8 5 2 9 5 5]
 [1 3 2 8 6 6 0 8 0 4]
 [9 9 0 3 2 8 9 7 3 7]
 [0 2 1 6 8 1 7 3 4 4]
 [4 5 8 5 2 4 6 7 5 9]
 [8 2 9 2 7 9 8 7 5 7]]


In [26]:

for i in x: #prints ever row in x
  for j in i: #j access all the elements in i
    #if (j%2 !=0):
      #j.replace( j, "@")
    np.where(j==0,j,"@")
    
    #print (j)

In [27]:
print(x)

[[0 6 8 3 9 4 6 6 1 0]
 [0 1 0 2 2 7 4 2 4 9]
 [5 4 9 8 3 2 3 7 9 2]
 [0 0 4 4 4 6 2 9 1 5]
 [5 3 8 9 8 5 2 9 5 5]
 [1 3 2 8 6 6 0 8 0 4]
 [9 9 0 3 2 8 9 7 3 7]
 [0 2 1 6 8 1 7 3 4 4]
 [4 5 8 5 2 4 6 7 5 9]
 [8 2 9 2 7 9 8 7 5 7]]


In [3]:
#for i in x: #prints ever row
    #print (i)

[0 6 8 3 9 4 6 6 1 0]
[0 1 0 2 2 7 4 2 4 9]
[5 4 9 8 3 2 3 7 9 2]
[0 0 4 4 4 6 2 9 1 5]
[5 3 8 9 8 5 2 9 5 5]
[1 3 2 8 6 6 0 8 0 4]
[9 9 0 3 2 8 9 7 3 7]
[0 2 1 6 8 1 7 3 4 4]
[4 5 8 5 2 4 6 7 5 9]
[8 2 9 2 7 9 8 7 5 7]


In [ ]:
from numpy import random

x = random.randint(10, size=(10, 10))

print(x)